if(EXISTS "/root/miniob/test/case/unittest/bitmap_test[1]_tests.cmake")
  include("/root/miniob/test/case/unittest/bitmap_test[1]_tests.cmake")
else()
  add_test(bitmap_test_NOT_BUILT bitmap_test_NOT_BUILT)
endif()
