if(EXISTS "/root/miniob/test/case/unittest/clog_test[1]_tests.cmake")
  include("/root/miniob/test/case/unittest/clog_test[1]_tests.cmake")
else()
  add_test(clog_test_NOT_BUILT clog_test_NOT_BUILT)
endif()
