add_test([=[Expected equality of these values:.pid]=]  /home/lyhkk/miniob/bin/pidfile_test [==[--gtest_filter=Expected equality of these values:.pid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Expected equality of these values:.pid]=]  PROPERTIES WORKING_DIRECTORY /home/lyhkk/miniob/unittest SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Expected equality of these values:.Which is: 15872]=]  /home/lyhkk/miniob/bin/pidfile_test [==[--gtest_filter=Expected equality of these values:.Which is: 15872]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Expected equality of these values:.Which is: 15872]=]  PROPERTIES WORKING_DIRECTORY /home/lyhkk/miniob/unittest SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Expected equality of these values:.target]=]  /home/lyhkk/miniob/bin/pidfile_test [==[--gtest_filter=Expected equality of these values:.target]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Expected equality of these values:.target]=]  PROPERTIES WORKING_DIRECTORY /home/lyhkk/miniob/unittest SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Expected equality of these values:.Which is: 13187]=]  /home/lyhkk/miniob/bin/pidfile_test [==[--gtest_filter=Expected equality of these values:.Which is: 13187]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Expected equality of these values:.Which is: 13187]=]  PROPERTIES WORKING_DIRECTORY /home/lyhkk/miniob/unittest SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  pidfile_test_TESTS [==[Expected equality of these values:.pid]==] [==[Expected equality of these values:.Which is: 15872]==] [==[Expected equality of these values:.target]==] [==[Expected equality of these values:.Which is: 13187]==])
